# Generated by Django 5.2.3 on 2025-06-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='hero/')),
                ('titulo', models.CharField(blank=True, max_length=100)),
                ('subtitulo', models.CharField(blank=True, max_length=200)),
                ('boton_texto', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, verbose_name='Enlace destino')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar los slides')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
