services:
  - type: web
    name: tumbesfc
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py shell < create_superuser.py
    startCommand: "gunicorn tumbesfc.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tumbesfc.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - fromDatabase:
          name: tumbesfc-db
          property: connectionString
          key: DATABASE_URL
    autoDeploy: true
databases:
  - name: tumbesfc-db
    plan: free