# Generated by Django 5.2.3 on 2025-06-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('resumen', models.TextField()),
                ('cuerpo', models.TextField()),
                ('imagen', models.ImageField(upload_to='noticias/')),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
