# Generated by Django 5.2.3 on 2025-06-24 16:14

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='imagen',
            field=models.ImageField(storage=storages.backends.s3.S3Storage(), upload_to='sponsors/'),
        ),
    ]
