# Generated by Django 5.2.3 on 2025-06-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='finalizado',
            field=models.BooleanField(default=False, verbose_name='¿Ya jugado?'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goleadores_local',
            field=models.CharField(blank=True, max_length=250, verbose_name='Goleadores Tumbes FC'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goleadores_visitante',
            field=models.CharField(blank=True, max_length=250, verbose_name='Goleadores rival'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles Tumbes FC'),
        ),
        migrations.AddField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Goles rival'),
        ),
        migrations.AddField(
            model_name='partido',
            name='liga',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='logo_visitante',
            field=models.ImageField(blank=True, null=True, upload_to='logos_visitantes/'),
        ),
    ]
