# Generated by Django 5.2.3 on 2025-06-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0002_partido_finalizado_partido_goleadores_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles Tumbes FC'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Goles rival'),
        ),
    ]
