# Generated by Django 5.2.3 on 2025-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0003_alter_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goles Tumbes FC'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Goles rival'),
        ),
    ]
