# Generated by Django 5.2.3 on 2025-06-24 16:14

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidos', '0004_alter_partido_goles_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='logo_visitante',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='logos_visitantes/'),
        ),
    ]
